"""'Init'

Revision ID: 957e47048ae6
Revises: ff2b8f3491a6
Create Date: 2023-06-24 10:16:47.380434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957e47048ae6'
down_revision = 'ff2b8f3491a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
